services:
  - type: web
    name: hrms-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: SECRET_KEY
        value: "replace-with-secure-secret"
      - key: ALLOWED_HOSTS
        value: "hrms-assesment-ghrr.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend.com"
      - key: DB_NAME
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: DB_HOST
        value: ""
      - key: DB_PORT
        value: "5432"
